# Generated by Django 4.2.7 on 2023-11-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='body_armor',
            name='agility',
            field=models.IntegerField(blank=True, null=True, verbose_name='сила'),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='equipment_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='требуемый уровень'),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='item_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='уровень предмета'),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='type_armor',
            field=models.CharField(default=1, max_length=200, verbose_name='тип брони'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='armor_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='рейтинг брони'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='intelligence',
            field=models.IntegerField(blank=True, null=True, verbose_name='интеллект'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='strength',
            field=models.IntegerField(blank=True, null=True, verbose_name='сила'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='название'),
        ),
    ]
