# Generated by Django 4.2.7 on 2023-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0002_body_armor_agility_body_armor_equipment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_armor',
            name='type_armor',
            field=models.CharField(default='', max_length=100, verbose_name='тип брони'),
        ),
    ]
