# Generated by Django 4.2.7 on 2023-11-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0004_alter_body_armor_type_armor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body_armor',
            name='armor_rate',
        ),
        migrations.RemoveField(
            model_name='body_armor',
            name='equipment_level',
        ),
        migrations.RemoveField(
            model_name='body_armor',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='body_armor',
            name='item_level',
        ),
        migrations.RemoveField(
            model_name='body_armor',
            name='type_armor',
        ),
        migrations.AddField(
            model_name='body_armor',
            name='armor',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='armor_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='crit_rating',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='haste_rating',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='item_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='level',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='quality',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='required_level',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='stamina',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='body_armor',
            name='versatility',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='agility',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='strength',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
