# Generated by Django 4.2.7 on 2023-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0007_rename_level_body_armor_item_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_armor',
            name='agility',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ловкость'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='armor',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='броня'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='crit_rating',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='крит'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='haste_rating',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='скорость'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='intelect',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='интелект'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='mastery',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='искустность'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='stamina',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='выносливость'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='strength',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='сила'),
        ),
        migrations.AlterField(
            model_name='body_armor',
            name='versatility',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='универсальность'),
        ),
    ]
