# Generated by Django 4.2.7 on 2023-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0008_alter_body_armor_agility_alter_body_armor_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_armor',
            name='required_level',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='уровень для экиперовки'),
        ),
    ]
