# Generated by Django 4.2.7 on 2023-11-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0010_head_armor_alter_body_armor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='body_armor',
            name='item_img',
            field=models.URLField(default=None, verbose_name='ссылка на изорбажение предмета'),
        ),
        migrations.AddField(
            model_name='head_armor',
            name='item_img',
            field=models.URLField(default=None, verbose_name='ссылка на изорбажение предмета'),
        ),
    ]
