# Generated by Django 4.2.7 on 2023-11-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0011_body_armor_item_img_head_armor_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_armor',
            name='required_level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='уровень для экиперовки'),
        ),
    ]
