# Generated by Django 4.2.7 on 2023-11-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0012_alter_body_armor_required_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_armor',
            name='required_level',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='уровень для экиперовки'),
        ),
    ]
