# Generated by Django 4.2.7 on 2023-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0015_amulet_back_armor_belt_armor_legs_armor_ring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='attack_speed',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='скорость 1 удара'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage_per_second',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='урон за секунду'),
        ),
    ]
