# Generated by Django 4.2.7 on 2023-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0016_weapon_attack_speed_weapon_damage_per_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt_armor',
            name='item_img',
            field=models.URLField(default='https://static.wikia.nocookie.net/wowpedia/images/c/cd/Ui-paperdoll-slot-waist.png/revision/latest?cb=20070607015409', verbose_name='ссылка на изорбажение предмета'),
        ),
    ]
