# Generated by Django 4.2.7 on 2023-11-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0018_alter_belt_armor_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trinket',
            name='enique_spell',
        ),
        migrations.AddField(
            model_name='trinket',
            name='unique_spell',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='уникальная способность предмета'),
        ),
    ]
