# Generated by Django 4.2.7 on 2023-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0019_remove_trinket_enique_spell_trinket_unique_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='max_damage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='максимальный урон'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='min_damage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='минимальный урон'),
        ),
    ]
