# Generated by Django 4.2.7 on 2023-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0021_alter_weapon_attack_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='crit_rating',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='крит'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='haste_rating',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='скорость'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='mastery',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='искустность'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='versatility',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='универсальность'),
        ),
    ]
