# Generated by Django 4.2.4 on 2023-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0022_alter_weapon_crit_rating_alter_weapon_haste_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gloves_armor',
            options={'ordering': ('-id',), 'verbose_name': 'перчаптки', 'verbose_name_plural': 'перчаптки'},
        ),
        migrations.AlterField(
            model_name='belt_armor',
            name='item_img',
            field=models.URLField(default='https://static.wikia.nocookie.net/wowpedia/images/c/cd/Ui-paperdoll-slot-waist.png/revision/latest?cb=20070607015409', verbose_name='ссылка на изорбажение предмета'),
        ),
    ]
