# Generated by Django 4.2.7 on 2023-11-16 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wow_db', '0013_alter_body_armor_required_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название подкласса')),
                ('class_logo', models.ImageField(upload_to='images/', verbose_name='лого подкласса')),
            ],
        ),
        migrations.CreateModel(
            name='Game_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название класса')),
                ('class_logo', models.ImageField(upload_to='images/', verbose_name='лого класса')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_characters.game_specialization', verbose_name='подкласс')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=28, unique=True, verbose_name='никнейм')),
                ('gender', models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], default='Male', max_length=22, verbose_name='пол персонажа')),
                ('character_level', models.IntegerField(blank=True, default=70, null=True, verbose_name='уровень персонажа')),
                ('fraction', models.CharField(choices=[('Horde', 'Орда'), ('Alliance', 'Альянс')], default='Horde', max_length=22, verbose_name='фракция')),
                ('race', models.CharField(choices=[('Orc', 'Орк'), ('Human', 'Человек'), ('Bood Elf', 'Эльф крови'), ('Night Elf', 'Ночной эльф'), ('Goblin', 'Гоблин'), ('Tauren', 'Корова'), ('Troll', 'Троль'), ('Undead', 'Нежить'), ('Pandaren', 'Панда'), ('Gnome', 'Гном'), ('Dwarf', 'Дворф'), ('Draeneir', 'Дреней'), ('Worgen', 'Ворген')], default='Orc', max_length=22, verbose_name='расса')),
                ('pvp_raiting', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='пвп рейтинг')),
                ('pve_raiting', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='пве рейтинг')),
                ('str', models.IntegerField(blank=True, default=0, null=True, verbose_name='сила')),
                ('stamina', models.IntegerField(blank=True, default=0, null=True, verbose_name='выносливость')),
                ('intellect', models.IntegerField(blank=True, default=0, null=True, verbose_name='интелект')),
                ('agi', models.IntegerField(blank=True, default=0, null=True, verbose_name='ловкость')),
                ('crit', models.IntegerField(blank=True, default=0, null=True, verbose_name='крит')),
                ('haste_rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='скорость')),
                ('versatility', models.IntegerField(blank=True, default=0, null=True, verbose_name='универсальность')),
                ('masteryy', models.IntegerField(blank=True, default=0, null=True, verbose_name='исскустность')),
                ('armor_rate', models.IntegerField(blank=True, default=0, null=True, verbose_name='броня')),
                ('health', models.IntegerField(blank=True, default=100, null=True, verbose_name='здоровье')),
                ('mana', models.IntegerField(blank=True, default=100, null=True, verbose_name='мана')),
                ('damage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Урон')),
                ('magical_damage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Магический урон')),
                ('body_armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.body_armor', verbose_name='нагудник')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_characters.game_class', verbose_name='класс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
