# Generated by Django 4.2.7 on 2023-11-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0013_alter_body_armor_required_level'),
        ('game_characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='head_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.head_armor', verbose_name='нагудник'),
        ),
    ]
