# Generated by Django 4.2.7 on 2023-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pve_raiting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='пве рейтинг'),
        ),
        migrations.AddField(
            model_name='character',
            name='pvp_raiting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='пвп рейтинг'),
        ),
    ]
