# Generated by Django 4.2.7 on 2023-11-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0016_weapon_attack_speed_weapon_damage_per_second'),
        ('game_characters', '0002_character_head_armor'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='amulet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.amulet', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='back_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.back_armor', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='belt_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.belt_armor', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='boots_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.boots_armor', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='gloves_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.gloves_armor', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='legs_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.legs_armor', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='ring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.ring', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='shoulder_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.shoulder_armor', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='trinket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.trinket', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.weapon', verbose_name='ботинки'),
        ),
        migrations.AddField(
            model_name='character',
            name='wrist_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.wrist_armor', verbose_name='ботинки'),
        ),
    ]
