# Generated by Django 4.2.7 on 2023-11-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0004_alter_body_armor_type_armor'),
        ('game_characters', '0002_character_pve_raiting_character_pvp_raiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='body_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_db.body_armor', verbose_name='нагудник'),
        ),
    ]
