# Generated by Django 4.2.7 on 2023-11-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wow_db', '0018_alter_belt_armor_item_img'),
        ('game_characters', '0003_character_amulet_character_back_armor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='ring',
        ),
        migrations.RemoveField(
            model_name='character',
            name='trinket',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.AddField(
            model_name='character',
            name='ring1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='кольцо_1', to='wow_db.ring'),
        ),
        migrations.AddField(
            model_name='character',
            name='ring2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='кольцо_2', to='wow_db.ring'),
        ),
        migrations.AddField(
            model_name='character',
            name='trinket1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='тринкет_1', to='wow_db.trinket'),
        ),
        migrations.AddField(
            model_name='character',
            name='trinket2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='тринкет_2', to='wow_db.trinket'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_hand_weapons', to='wow_db.weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_hand_weapons', to='wow_db.weapon'),
        ),
    ]
