# Generated by Django 4.2.4 on 2023-12-02 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0004_remove_character_ring_remove_character_trinket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='тип брони')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='тип оружия')),
            ],
        ),
        migrations.AddField(
            model_name='game_class',
            name='class_armor_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_characters.armor_type', verbose_name='тип используемой экиперовки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_class',
            name='class_weapon_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_characters.weapon_type', verbose_name='тип используемого оружия'),
            preserve_default=False,
        ),
    ]
