# Generated by Django 4.2.7 on 2023-11-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0004_character_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название подкласса')),
                ('class_logo', models.ImageField(upload_to='images/', verbose_name='лого подкласса')),
            ],
        ),
        migrations.AddField(
            model_name='game_class',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_characters.game_specialization', verbose_name='подкласс'),
            preserve_default=False,
        ),
    ]
