# Generated by Django 4.2.4 on 2023-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0005_armor_type_weapon_type_game_class_class_armor_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_class',
            name='class_weapon_type',
        ),
        migrations.AddField(
            model_name='game_class',
            name='class_weapon_type',
            field=models.ManyToManyField(to='game_characters.weapon_type', verbose_name='тип используемого оружия'),
        ),
    ]
