# Generated by Django 4.2.7 on 2023-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0006_character_agi_character_armor_rate_character_crit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('мужчина', 'Male'), ('женщина', 'Female')], default='мужчина', max_length=22, verbose_name='пол персонажа'),
        ),
    ]
