# Generated by Django 4.2.7 on 2023-11-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0008_alter_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='fraction',
            field=models.CharField(choices=[('Орда', 'Horde'), ('Альянс', 'Alience')], default='Орда', max_length=22, verbose_name='Фракция'),
        ),
    ]
