# Generated by Django 4.2.7 on 2023-11-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0009_alter_character_fraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='fraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_characters.game_fraction', verbose_name='фракция'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], default='Male', max_length=22, verbose_name='пол персонажа'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Orc', 'Орк'), ('Human', 'Человек'), ('Bood Elf', 'Эльф крови'), ('Night Elf', 'Ночной эльф'), ('Goblin', 'Гоблин'), ('Tauren', 'Корова'), ('Troll', 'Троль'), ('Undead', 'Нежить'), ('Pandaren', 'Панда'), ('Gnome', 'Гном'), ('Dwarf', 'Дворф'), ('Draeneir', 'Дреней')], default='Orc', max_length=22, verbose_name='расса'),
        ),
        migrations.DeleteModel(
            name='Game_race',
        ),
    ]
