# Generated by Django 4.2.7 on 2023-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0010_alter_character_fraction_alter_character_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='fraction',
            field=models.CharField(choices=[('Horde', 'Орда'), ('Alliance', 'Альянс')], max_length=22, verbose_name='фракция'),
        ),
        migrations.DeleteModel(
            name='Game_fraction',
        ),
    ]
