# Generated by Django 4.2.7 on 2023-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/default_avatar.png', null=True, upload_to='avatars/', verbose_name='аватарка'),
        ),
    ]
